### ISSUE TITLE
Update docs to help the compiler-impaired :)

### ISSUE THREAD

**Issue by rslifka** [newobj/nginx-x-rid-header#1]
In addition to --with-ld-opt you also need --with-cc-opt so that the header files can be found during compilation.  Here's what worked for us:

(1) On Ubuntu 10.04 LTS, you'll need the libossp-uuid-dev package.

(2) Use these opts when compiling:

```
--with-ld-opt=-lossp-uuid
--with-cc-opt=-I/usr/include/ossp
```

UUIDs working great, thanks for this!

Rob

**Comment by doubaokun** [comment]
This works for me.

**Comment by luis-alen** [comment]
This worked for me too on Ubuntu 12.10. By the way, I also needed the uuid-dev package.

Finally, it's worth pointing out that it also requires the stub_status_module (--with-http_stub_status_module), otherwise it won't compile.

**Comment by odedfos** [comment]
So to sum things up:
 $ sudo apt-get install libpcre3-dev uuid-dev uuid-dev
and then:
$ ./configure --with-http_stub_status_module --with-cc-opt=-I/usr/include/ossp --with-ld-opt=-lossp-uuid --add-module=../nginx-x -rid-header
